spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  mvc:
    static-path-pattern: /image/**
  datasource:
    url: jdbc:mysql://localhost:3306/spin?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root